### ISSUE TITLE
differences between function norm reg and activity reg in Keras

### ISSUE THREAD

**Issue by yield22** [AmalRT/DNN_Reg#1]
see http://keras.io/regularizers/ for activity reg. Is l2 norm of activity the same as function norm defined in the paper under data distribution?

**Comment by AmalRT** [comment]
Thanks for pointing out this similarity.  Are you aware of a citable publication that describes "activity regularization"?  From what we can see, the most important difference is that we do not use the training data for our regularization scheme using the data distribution.  We believe this is an important point.  Although E_{x~p}[f(x)] + E_{x~p}[g(x)] = E_{x~p}[f(x) + g(x)], their convergence can be very different from a finite sample.
